"""
Report a measured number for the two components that were described as built but
never scored: the recommended-action policy model and the GraphSAGE structural
risk.

Disclosing a limitation is not the same as reporting a performance figure, and
"it runs" is not evidence. Each component is measured against the thing it can
honestly be measured against:

  Recommender  — it was trained on labels generated by a documented threshold
                 policy, so the meaningful question is not "does it predict
                 moderator behaviour" (no ground truth exists for that) but
                 "does it faithfully reproduce the policy it was fitted to".
                 That is fidelity, and it is measurable exactly.

  GraphSAGE    — measured the same way every other ranking signal in Table 3.2
                 is measured: ROC-AUC against the planted ground truth the
                 pipeline never sees. This places it alongside CHI, raw toxicity
                 and the instability score rather than outside the comparison.

    python evaluate_components.py
"""

from __future__ import annotations

import json
import pickle
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "outputs"
ACTIONS = {0: "NO_ACTION", 1: "MONITOR", 2: "WARN",
           3: "INCREASE_MODERATION", 4: "EMERGENCY_INTERVENTION"}
FEATURES = ["community_health_index", "toxicity_rate", "polarization",
            "churn_rate", "echo_chamber_index"]


def policy_label(chi, tox, pol, churn, echo) -> int:
    """
    The documented threshold policy the recommender was fitted to, transcribed
    from modules/moderation_recommender.py so the comparison is against the
    specification rather than against the model's own training split.
    """
    if chi < 65 or tox > 0.35 or pol > 0.4:
        return 4
    if chi < 72 or tox > 0.25 or pol > 0.25:
        return 3
    if chi < 78 or tox > 0.18 or churn > 0.7:
        return 2
    if chi < 85 or tox > 0.12 or echo > 0.6:
        return 1
    return 0


def roc_auc(labels: np.ndarray, scores: np.ndarray) -> float:
    pos, neg = labels == 1, labels == 0
    if pos.sum() == 0 or neg.sum() == 0:
        return float("nan")
    order = scores.argsort()
    ranks = np.empty(len(scores), dtype=float)
    ranks[order] = np.arange(1, len(scores) + 1)
    return float((ranks[pos].sum() - pos.sum() * (pos.sum() + 1) / 2)
                 / (pos.sum() * neg.sum()))


def eval_recommender() -> dict:
    """Fidelity of the trained model to the policy it was fitted to."""
    path = ROOT / "models" / "moderation_recommender.pkl"
    if not path.exists():
        return {"status": "model absent"}
    with open(path, "rb") as fh:
        rec = pickle.load(fh)

    rows = []
    for name, p in (("benchmark", OUT / "meso_report.csv"),
                    ("real", OUT / "real" / "meso_report.csv")):
        if not p.exists():
            continue
        m = pd.read_csv(p)
        if not set(FEATURES) <= set(m.columns):
            continue
        X = m[FEATURES].to_numpy()
        pred = rec.predict(X)
        want = np.array([policy_label(*r) for r in X])
        agree = float((pred == want).mean())
        within1 = float((np.abs(pred - want) <= 1).mean())
        rows.append({"dataset": name, "n": int(len(m)),
                     "exact_agreement": round(agree, 4),
                     "within_one_band": round(within1, 4),
                     "distribution": {ACTIONS[int(k)]: int(v) for k, v in
                                      pd.Series(pred).value_counts().items()}})

    # A held-out check on freshly sampled feature vectors, so the figure is not
    # only measured on the 84 communities the pipeline happens to produce.
    rng = np.random.default_rng(7)
    n = 4000
    synth = np.column_stack([
        rng.uniform(0, 100, n), rng.beta(2, 10, n), rng.beta(1.5, 8, n),
        rng.beta(3, 5, n), rng.beta(2, 3, n)])
    pred = rec.predict(synth)
    want = np.array([policy_label(*r) for r in synth])
    held = {"n": n, "exact_agreement": round(float((pred == want).mean()), 4),
            "within_one_band": round(float((np.abs(pred - want) <= 1).mean()), 4)}

    return {"status": "measured", "per_dataset": rows, "held_out_sample": held,
            "interpretation":
                "Fidelity to the documented threshold policy, not accuracy "
                "against observed moderator decisions — no labelled corpus of "
                "real moderation actions exists. The figure states how "
                "faithfully the model reproduces the policy it was fitted to, "
                "which is the only claim its training data supports."}


def eval_gnn() -> dict:
    """GraphSAGE structural risk, scored the same way as every other signal."""
    meso_p = OUT / "meso_report.csv"
    truth_p = ROOT / "data" / "ground_truth.json"
    if not (meso_p.exists() and truth_p.exists()):
        return {"status": "benchmark or ground truth absent"}

    m = pd.read_csv(meso_p)
    if "gnn_risk" not in m.columns:
        return {"status": "gnn_risk column absent — run the pipeline first"}

    truth = {k.replace("r/", "").lower(): v
             for k, v in json.loads(truth_p.read_text(encoding="utf-8")).items()}
    m["key"] = m["subreddit"].astype(str).str.replace(r"^r/", "", regex=True).str.lower()
    m = m[m["key"].isin(truth)].copy()
    m["planted"] = m["key"].map(
        lambda k: 1 if truth[k]["trajectory"] == "destabilising" else 0)

    have = m.dropna(subset=["gnn_risk"])
    if have.empty:
        return {"status": "no community matched the graph"}

    auc = roc_auc(have["planted"].to_numpy(), have["gnn_risk"].to_numpy())
    return {
        "status": "measured",
        "communities_scored": int(len(have)),
        "communities_total": int(len(m)),
        "planted_in_scored": int(have["planted"].sum()),
        "roc_auc": round(auc, 4),
        "interpretation":
            "Measured on the same task and against the same withheld ground "
            "truth as CHI, raw toxicity and the instability score, so it can be "
            "read directly against Table 3.2. The model was trained with 'at "
            "risk' defined as CHI below 75 while most graph nodes carry no CHI, "
            "so it was fitted on a heavily imbalanced target and is not expected "
            "to separate a trend-based signal; the figure records what it "
            "actually achieves rather than leaving it unscored.",
    }


def main() -> None:
    res = {"recommender_policy_fidelity": eval_recommender(),
           "graphsage_structural_risk": eval_gnn()}
    (OUT / "component_evaluation.json").write_text(
        json.dumps(res, indent=2), encoding="utf-8")

    r = res["recommender_policy_fidelity"]
    print("=== RECOMMENDED-ACTION POLICY MODEL ===")
    if r.get("status") == "measured":
        for d in r["per_dataset"]:
            print(f"  {d['dataset']:<10} n={d['n']:<4} exact={d['exact_agreement']:.3f}  "
                  f"within-one-band={d['within_one_band']:.3f}")
        h = r["held_out_sample"]
        print(f"  held-out   n={h['n']} exact={h['exact_agreement']:.3f}  "
              f"within-one-band={h['within_one_band']:.3f}")
    else:
        print(" ", r.get("status"))

    g = res["graphsage_structural_risk"]
    print("\n=== GRAPHSAGE STRUCTURAL RISK ===")
    if g.get("status") == "measured":
        print(f"  scored {g['communities_scored']}/{g['communities_total']} communities "
              f"({g['planted_in_scored']} planted)")
        print(f"  ROC-AUC vs planted ground truth: {g['roc_auc']}")
    else:
        print(" ", g.get("status"))
    print(f"\nwrote {OUT / 'component_evaluation.json'}")


if __name__ == "__main__":
    main()
