#!/usr/bin/env python3
"""
Every number in Tables 1-4 and Section 5.6 of the audit paper, from the
committed outputs. Paths resolve relative to the repository root, so this
runs from anywhere with no configuration:

    python docs/paper/bootstrap_ci.py

Inputs (all committed except where noted):
  outputs/meso_report.csv          benchmark meso layer, 60 communities
  data/ground_truth.json           planted trajectories, never read by the pipeline
  outputs/forecast_results.csv     TFT five-day p10/p50/p90 per benchmark community
  outputs/real/meso_report.csv     the same layer on the real 24-community corpus
  data/apollo_daily.csv            benchmark daily series (regenerated by
                                   simulate_data.py; Table 4's OLS rows need it)

Output:
  docs/paper/results.json          consumed by make_paper_figures.py and quoted
                                   verbatim in the paper.

Method: ROC-AUC via the Mann-Whitney statistic with average ranks (ties are
abundant, see Finding 1). Confidence intervals by bootstrap over communities,
percentile method, N_BOOT resamples, seed SEED. Paired comparisons compute
both AUCs on the same resample; resamples with no positives or no negatives
are dropped under one shared mask so the paired arrays stay aligned.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import kendalltau, rankdata, spearmanr

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "paper" / "results.json"

SEED = 20260903
N_BOOT = 20_000


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def auc(score: np.ndarray, y: np.ndarray) -> float:
    """ROC-AUC = P(score_pos > score_neg) + 0.5 P(tie), via average ranks."""
    r = rankdata(score)
    n1 = int(y.sum())
    n0 = len(y) - n1
    if n1 == 0 or n0 == 0:
        return float("nan")
    return float((r[y == 1].sum() - n1 * (n1 + 1) / 2) / (n1 * n0))


def boot_indices(n: int, rng: np.random.Generator) -> np.ndarray:
    return rng.integers(0, n, size=(N_BOOT, n))


def boot_aucs(scores: dict[str, np.ndarray], y: np.ndarray, idx: np.ndarray) -> dict[str, np.ndarray]:
    """AUC of every signal on every resample. Degenerate resamples -> NaN."""
    out = {k: np.full(N_BOOT, np.nan) for k in scores}
    for b in range(N_BOOT):
        ii = idx[b]
        yb = y[ii]
        if yb.sum() == 0 or yb.sum() == len(yb):
            continue
        for k, s in scores.items():
            out[k][b] = auc(s[ii], yb)
    return out


def ci(a: np.ndarray) -> tuple[float, float]:
    a = a[~np.isnan(a)]
    return float(np.percentile(a, 2.5)), float(np.percentile(a, 97.5))


def r3(x: float) -> float:
    return round(float(x), 3)


def strip(name: str) -> str:
    return name[2:] if name.startswith("r/") else name


# --------------------------------------------------------------------------- #
# benchmark: Tables 1-3
# --------------------------------------------------------------------------- #
truth = json.loads((ROOT / "data" / "ground_truth.json").read_text())
meso = pd.read_csv(ROOT / "outputs" / "meso_report.csv")
meso["key"] = meso["subreddit"].map(strip)
meso["planted"] = meso["key"].map(lambda k: truth[k]["trajectory"] == "destabilising").astype(int)
y = meso["planted"].to_numpy()
n, n_pos = len(meso), int(y.sum())

signals = {
    "instability": meso["instability_score"].to_numpy(float),
    "toxicity": meso["toxicity_rate"].to_numpy(float),
    "chi_low_first": -meso["community_health_index"].to_numpy(float),
    "trend_only": meso["toxicity_trend"].to_numpy(float),
    "churn": meso["churn_rate"].to_numpy(float),
    "polarisation": meso["polarization"].to_numpy(float),
    "echo": meso["echo_chamber_index"].to_numpy(float),
}

table1 = {}
for col, key, weight in [
    ("toxicity_rate", "toxicity", 35),
    ("polarization", "polarisation", 30),
    ("echo_chamber_index", "echo", 15),
    ("churn_rate", "churn", 20),
]:
    v = meso[col].to_numpy(float)
    vc = pd.Series(v).value_counts()
    table1[key] = {
        "weight": weight,
        "distinct": int(vc.size),
        "modal_count": int(vc.iloc[0]),
        "auc": r3(auc(v, y)),
    }

rng = np.random.default_rng(SEED)
idx = boot_indices(n, rng)
B = boot_aucs(signals, y, idx)
mask = ~np.isnan(B["toxicity"])  # shared degeneracy mask

table2 = {}
for k in ("instability", "toxicity", "chi_low_first", "trend_only"):
    lo, hi = ci(B[k])
    table2[k] = {"auc": r3(auc(signals[k], y)), "ci": [r3(lo), r3(hi)]}

table3 = {}
for a_, b_ in (("toxicity", "chi_low_first"), ("instability", "chi_low_first")):
    d = (B[a_] - B[b_])[mask]
    lo, hi = np.percentile(d, [2.5, 97.5])
    table3[f"{a_}_minus_{b_}"] = {
        "delta": r3(auc(signals[a_], y) - auc(signals[b_], y)),
        "ci": [r3(lo), r3(hi)],
        "p_gt_0": r3((d > 0).mean()),
    }

# --------------------------------------------------------------------------- #
# benchmark: Table 4 (trajectory detection from the daily series)
# --------------------------------------------------------------------------- #
table4: dict = {}

# TFT: slope of the five-day p50 forecast path, as validate_simulation.py does.
fc = pd.read_csv(ROOT / "outputs" / "forecast_results.csv")
fc["key"] = fc["subreddit"].map(strip)
tft_slope = (
    fc.sort_values(["key", "day"])
    .groupby("key")
    .apply(lambda g: float(np.polyfit(g["day"], g["p50"], 1)[0]), include_groups=False)
)
tft_slope = tft_slope.reindex(meso["key"]).to_numpy(float)
assert not np.isnan(tft_slope).any(), "forecast_results.csv is missing communities"
slope_signals = {"tft": tft_slope}

daily_path = ROOT / "data" / "apollo_daily.csv"
if daily_path.exists():
    daily = pd.read_csv(daily_path)
    daily["key"] = daily["subreddit"].map(strip)
    daily = daily.sort_values(["key", "time_idx"])

    def ols(g: pd.DataFrame, last: int | None = None) -> float:
        if last is not None:
            g = g.tail(last)
        return float(np.polyfit(g["time_idx"], g["avg_toxicity"], 1)[0])

    full = daily.groupby("key").apply(ols, include_groups=False).reindex(meso["key"]).to_numpy(float)
    last30 = (
        daily.groupby("key").apply(lambda g: ols(g, 30), include_groups=False).reindex(meso["key"]).to_numpy(float)
    )
    slope_signals["ols_full"] = full
    slope_signals["ols_last30"] = last30
else:
    print(f"note: {daily_path.relative_to(ROOT)} not present; Table 4 OLS rows skipped "
          "(regenerate it with simulate_data.py)")

S = boot_aucs(slope_signals, y, idx)
for k, s in slope_signals.items():
    lo, hi = ci(S[k])
    table4[k] = {"auc": r3(auc(s, y)), "ci": [r3(lo), r3(hi)]}
if "ols_full" in slope_signals:
    d = (S["ols_full"] - S["tft"])[mask]
    lo, hi = np.percentile(d, [2.5, 97.5])
    table4["ols_full_minus_tft"] = {
        "delta": r3(auc(slope_signals["ols_full"], y) - auc(tft_slope, y)),
        "ci": [r3(lo), r3(hi)],
        "p_gt_0": r3((d > 0).mean()),
    }
tft_by_traj = pd.Series(tft_slope, index=meso["key"]).groupby(
    meso["key"].map(lambda k: truth[k]["trajectory"]).to_numpy()
).mean()
table4["tft_recall"] = f"{int((tft_slope[y == 1] > 0).sum())}/{n_pos}"
table4["tft_mean_slope_by_trajectory"] = {k: round(float(v), 5) for k, v in tft_by_traj.items()}

# --------------------------------------------------------------------------- #
# real corpus: Section 5.6
# --------------------------------------------------------------------------- #
real = pd.read_csv(ROOT / "outputs" / "real" / "meso_report.csv")
chi = real["community_health_index"].to_numpy(float)
ins = real["instability_score"].to_numpy(float)
rho, p_rho = spearmanr(chi, -ins)
tau, p_tau = kendalltau(chi, -ins)
by_chi = list(real["subreddit"][np.argsort(chi, kind="stable")])          # lowest CHI first
by_ins = list(real["subreddit"][np.argsort(-ins, kind="stable")])         # highest instability first
moves = {s: abs(by_chi.index(s) - by_ins.index(s)) for s in by_chi}
real_section = {
    "n": int(len(real)),
    "spearman_rho": r3(rho), "spearman_p": r3(p_rho),
    "kendall_tau": r3(tau), "kendall_p": r3(p_tau),
    "moved_5_or_more": int(sum(m >= 5 for m in moves.values())),
    "largest_move": int(max(moves.values())),
    "largest_mover": max(moves, key=moves.get),
    "top5_shared": sorted(set(by_chi[:5]) & set(by_ins[:5])),
    "rank_by_chi": {s: i + 1 for i, s in enumerate(by_chi)},
    "rank_by_instability": {s: i + 1 for i, s in enumerate(by_ins)},
    "toxicity_sd_real": round(float(real["toxicity_rate"].std(ddof=0)), 3),
    "toxicity_sd_benchmark": round(float(meso["toxicity_rate"].std(ddof=0)), 3),
    "toxicity_range_real": [round(float(real["toxicity_rate"].min()), 3), round(float(real["toxicity_rate"].max()), 3)],
    "toxicity_range_benchmark": [round(float(meso["toxicity_rate"].min()), 3), round(float(meso["toxicity_rate"].max()), 3)],
    "graph_components_distinct_real": {
        "polarisation": int(real["polarization"].nunique()),
        "echo": int(real["echo_chamber_index"].nunique()),
    },
    "comments": int(real["total_comments"].sum()),
}
prov = ROOT / "outputs" / "real" / "data_provenance.json"
if prov.exists():
    real_section["provenance"] = json.loads(prov.read_text())

results = {
    "seed": SEED, "n_boot": N_BOOT, "n": n, "n_pos": n_pos,
    "benchmark_comments": int(meso["total_comments"].sum()),
    "table1": table1, "table2": table2, "table3": table3, "table4": table4,
    "real": real_section,
}
OUT.write_text(json.dumps(results, indent=2))
# Raw bootstrap draws, for Figure 6 (paired-difference histograms).
np.savez_compressed(
    OUT.with_name("bootstrap_draws.npz"),
    mask=mask,
    **{f"auc_{k}": v for k, v in B.items()},
    **{f"slope_{k}": v for k, v in S.items()},
)
print(json.dumps(results, indent=2))
